Add method to stop background update timer

diff --git a/git-live b/git-live
--- a/git-live
+++ b/git-live
@@ -106,6 +106,25 @@ startPuller() {
   echo "$unit" > /run/git-live/active-unit-information
 }
 
+stopPuller() {
+  if ! [[ -f /run/git-live/active-unit-information ]]; then
+    # Puller timer is already stopped
+    return 0
+  fi
+
+  unit_info=$(cat /run/git-live/active-unit-information)
+  local unit_info
+  if [[ "$unit_info" =~ ([^ ]+\.timer) ]]; then
+    timer_unit=${BASH_REMATCH[1]}
+    local timer_unit
+
+    systemctl stop "$timer_unit"
+    rm -f /run/git-live/active-unit-information
+  #else
+    # TODO Log failure somewhere?
+  fi
+}
+
 init() {
   assertBinary awk
   assertBinary base64
